# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  workflow_dispatch:

permissions: write-all

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Exe
        uses: eric2788/pyinstaller-build@master
        with:
          main: main
          artifact: formatting
          use-dependencies: true
          icon: 'icon.ico'
          no-console: true
    
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          files: |
            ./dist/formatting.exe
